// Curated locality list for the 8 supported cities.
// Each entry: { name: canonical display name, pincode: most common pincode for that locality }
// Pincode is a best-effort default — sellers can override it manually.

export interface LocalityOption {
  name: string
  pincode: string
  city: string
}

const MUMBAI: LocalityOption[] = [
  { name: 'Andheri East', pincode: '400069', city: 'Mumbai' },
  { name: 'Andheri West', pincode: '400058', city: 'Mumbai' },
  { name: 'Bandra East', pincode: '400051', city: 'Mumbai' },
  { name: 'Bandra West', pincode: '400050', city: 'Mumbai' },
  { name: 'Borivali East', pincode: '400066', city: 'Mumbai' },
  { name: 'Borivali West', pincode: '400092', city: 'Mumbai' },
  { name: 'Chembur', pincode: '400071', city: 'Mumbai' },
  { name: 'Colaba', pincode: '400005', city: 'Mumbai' },
  { name: 'Dadar', pincode: '400014', city: 'Mumbai' },
  { name: 'Dharavi', pincode: '400017', city: 'Mumbai' },
  { name: 'Ghatkopar East', pincode: '400077', city: 'Mumbai' },
  { name: 'Ghatkopar West', pincode: '400086', city: 'Mumbai' },
  { name: 'Goregaon East', pincode: '400063', city: 'Mumbai' },
  { name: 'Goregaon West', pincode: '400104', city: 'Mumbai' },
  { name: 'Juhu', pincode: '400049', city: 'Mumbai' },
  { name: 'Kandivali East', pincode: '400101', city: 'Mumbai' },
  { name: 'Kandivali West', pincode: '400067', city: 'Mumbai' },
  { name: 'Kurla', pincode: '400070', city: 'Mumbai' },
  { name: 'Lokhandwala', pincode: '400053', city: 'Mumbai' },
  { name: 'Lower Parel', pincode: '400013', city: 'Mumbai' },
  { name: 'Mahim', pincode: '400016', city: 'Mumbai' },
  { name: 'Malad East', pincode: '400097', city: 'Mumbai' },
  { name: 'Malad West', pincode: '400064', city: 'Mumbai' },
  { name: 'Matunga', pincode: '400019', city: 'Mumbai' },
  { name: 'Mulund East', pincode: '400081', city: 'Mumbai' },
  { name: 'Mulund West', pincode: '400080', city: 'Mumbai' },
  { name: 'Navi Mumbai', pincode: '400703', city: 'Mumbai' },
  { name: 'Powai', pincode: '400076', city: 'Mumbai' },
  { name: 'Santacruz East', pincode: '400055', city: 'Mumbai' },
  { name: 'Santacruz West', pincode: '400054', city: 'Mumbai' },
  { name: 'Sion', pincode: '400022', city: 'Mumbai' },
  { name: 'Thane', pincode: '400601', city: 'Mumbai' },
  { name: 'Versova', pincode: '400061', city: 'Mumbai' },
  { name: 'Vikhroli', pincode: '400083', city: 'Mumbai' },
  { name: 'Vile Parle East', pincode: '400057', city: 'Mumbai' },
  { name: 'Vile Parle West', pincode: '400056', city: 'Mumbai' },
  { name: 'Wadala', pincode: '400031', city: 'Mumbai' },
  { name: 'Worli', pincode: '400018', city: 'Mumbai' },
]

const PUNE: LocalityOption[] = [
  { name: 'Aundh', pincode: '411007', city: 'Pune' },
  { name: 'Baner', pincode: '411045', city: 'Pune' },
  { name: 'Balewadi', pincode: '411045', city: 'Pune' },
  { name: 'Bavdhan', pincode: '411021', city: 'Pune' },
  { name: 'Bibwewadi', pincode: '411037', city: 'Pune' },
  { name: 'Boat Club Road', pincode: '411001', city: 'Pune' },
  { name: 'Camp', pincode: '411001', city: 'Pune' },
  { name: 'Chinchwad', pincode: '411033', city: 'Pune' },
  { name: 'Deccan Gymkhana', pincode: '411004', city: 'Pune' },
  { name: 'Dhankawadi', pincode: '411043', city: 'Pune' },
  { name: 'Erandwane', pincode: '411004', city: 'Pune' },
  { name: 'Hadapsar', pincode: '411028', city: 'Pune' },
  { name: 'Hinjewadi', pincode: '411057', city: 'Pune' },
  { name: 'Karve Nagar', pincode: '411052', city: 'Pune' },
  { name: 'Katraj', pincode: '411046', city: 'Pune' },
  { name: 'Kharadi', pincode: '411014', city: 'Pune' },
  { name: 'Kothrud', pincode: '411038', city: 'Pune' },
  { name: 'Kondhwa', pincode: '411048', city: 'Pune' },
  { name: 'Koregaon Park', pincode: '411001', city: 'Pune' },
  { name: 'Magarpatta', pincode: '411028', city: 'Pune' },
  { name: 'Mohammed Wadi', pincode: '411060', city: 'Pune' },
  { name: 'Mundhwa', pincode: '411036', city: 'Pune' },
  { name: 'Nagar Road', pincode: '411014', city: 'Pune' },
  { name: 'Narayan Peth', pincode: '411030', city: 'Pune' },
  { name: 'Nibm Road', pincode: '411048', city: 'Pune' },
  { name: 'Pashan', pincode: '411021', city: 'Pune' },
  { name: 'Pimple Nilakh', pincode: '411027', city: 'Pune' },
  { name: 'Pimple Saudagar', pincode: '411027', city: 'Pune' },
  { name: 'Pimpri', pincode: '411017', city: 'Pune' },
  { name: 'Shivajinagar', pincode: '411005', city: 'Pune' },
  { name: 'Sinhagad Road', pincode: '411041', city: 'Pune' },
  { name: 'Sus Road', pincode: '411021', city: 'Pune' },
  { name: 'Undri', pincode: '411060', city: 'Pune' },
  { name: 'Viman Nagar', pincode: '411014', city: 'Pune' },
  { name: 'Wadgaon Sheri', pincode: '411014', city: 'Pune' },
  { name: 'Warje', pincode: '411052', city: 'Pune' },
  { name: 'Wagholi', pincode: '412207', city: 'Pune' },
  { name: 'Wanowrie', pincode: '411040', city: 'Pune' },
]

const BANGALORE: LocalityOption[] = [
  { name: 'Banashankari', pincode: '560070', city: 'Bangalore' },
  { name: 'Bannerghatta Road', pincode: '560076', city: 'Bangalore' },
  { name: 'Bellandur', pincode: '560103', city: 'Bangalore' },
  { name: 'BTM Layout', pincode: '560076', city: 'Bangalore' },
  { name: 'CV Raman Nagar', pincode: '560093', city: 'Bangalore' },
  { name: 'Domlur', pincode: '560071', city: 'Bangalore' },
  { name: 'Electronic City', pincode: '560100', city: 'Bangalore' },
  { name: 'Frazer Town', pincode: '560005', city: 'Bangalore' },
  { name: 'HAL', pincode: '560017', city: 'Bangalore' },
  { name: 'Hebbal', pincode: '560024', city: 'Bangalore' },
  { name: 'Hennur', pincode: '560043', city: 'Bangalore' },
  { name: 'HSR Layout', pincode: '560102', city: 'Bangalore' },
  { name: 'Indira Nagar', pincode: '560038', city: 'Bangalore' },
  { name: 'JP Nagar', pincode: '560078', city: 'Bangalore' },
  { name: 'Jayanagar', pincode: '560041', city: 'Bangalore' },
  { name: 'Kalyan Nagar', pincode: '560043', city: 'Bangalore' },
  { name: 'Kammanahalli', pincode: '560084', city: 'Bangalore' },
  { name: 'Koramangala', pincode: '560034', city: 'Bangalore' },
  { name: 'Kengeri', pincode: '560060', city: 'Bangalore' },
  { name: 'KR Puram', pincode: '560036', city: 'Bangalore' },
  { name: 'Magadi Road', pincode: '560023', city: 'Bangalore' },
  { name: 'Mahadevapura', pincode: '560048', city: 'Bangalore' },
  { name: 'Malleshwaram', pincode: '560003', city: 'Bangalore' },
  { name: 'Marathahalli', pincode: '560037', city: 'Bangalore' },
  { name: 'Mysore Road', pincode: '560026', city: 'Bangalore' },
  { name: 'Nagarbhavi', pincode: '560072', city: 'Bangalore' },
  { name: 'New BEL Road', pincode: '560054', city: 'Bangalore' },
  { name: 'Old Airport Road', pincode: '560017', city: 'Bangalore' },
  { name: 'Rajajinagar', pincode: '560010', city: 'Bangalore' },
  { name: 'Ramamurthy Nagar', pincode: '560016', city: 'Bangalore' },
  { name: 'RT Nagar', pincode: '560032', city: 'Bangalore' },
  { name: 'Sarjapur Road', pincode: '560035', city: 'Bangalore' },
  { name: 'Seshadripuram', pincode: '560020', city: 'Bangalore' },
  { name: 'Varthur', pincode: '560087', city: 'Bangalore' },
  { name: 'Whitefield', pincode: '560066', city: 'Bangalore' },
  { name: 'Yelahanka', pincode: '560064', city: 'Bangalore' },
  { name: 'Yeshwanthpur', pincode: '560022', city: 'Bangalore' },
]

const DELHI_NCR: LocalityOption[] = [
  { name: 'Connaught Place', pincode: '110001', city: 'Delhi NCR' },
  { name: 'Defence Colony', pincode: '110024', city: 'Delhi NCR' },
  { name: 'Dwarka', pincode: '110075', city: 'Delhi NCR' },
  { name: 'East of Kailash', pincode: '110065', city: 'Delhi NCR' },
  { name: 'Faridabad', pincode: '121001', city: 'Delhi NCR' },
  { name: 'Ghaziabad', pincode: '201001', city: 'Delhi NCR' },
  { name: 'Golf Course Road', pincode: '122002', city: 'Delhi NCR' },
  { name: 'Greater Kailash', pincode: '110048', city: 'Delhi NCR' },
  { name: 'Greater Noida', pincode: '201310', city: 'Delhi NCR' },
  { name: 'Gurgaon Sector 14', pincode: '122001', city: 'Delhi NCR' },
  { name: 'Gurgaon Sector 56', pincode: '122011', city: 'Delhi NCR' },
  { name: 'Hauz Khas', pincode: '110016', city: 'Delhi NCR' },
  { name: 'Janakpuri', pincode: '110058', city: 'Delhi NCR' },
  { name: 'Lajpat Nagar', pincode: '110024', city: 'Delhi NCR' },
  { name: 'MG Road Gurgaon', pincode: '122002', city: 'Delhi NCR' },
  { name: 'Mayur Vihar', pincode: '110091', city: 'Delhi NCR' },
  { name: 'Model Town', pincode: '110009', city: 'Delhi NCR' },
  { name: 'Nehru Place', pincode: '110019', city: 'Delhi NCR' },
  { name: 'Noida Sector 18', pincode: '201301', city: 'Delhi NCR' },
  { name: 'Noida Sector 62', pincode: '201309', city: 'Delhi NCR' },
  { name: 'Paharganj', pincode: '110055', city: 'Delhi NCR' },
  { name: 'Pitampura', pincode: '110034', city: 'Delhi NCR' },
  { name: 'Punjabi Bagh', pincode: '110026', city: 'Delhi NCR' },
  { name: 'Rajouri Garden', pincode: '110027', city: 'Delhi NCR' },
  { name: 'Rohini', pincode: '110085', city: 'Delhi NCR' },
  { name: 'Saket', pincode: '110017', city: 'Delhi NCR' },
  { name: 'South Extension', pincode: '110049', city: 'Delhi NCR' },
  { name: 'Vasant Kunj', pincode: '110070', city: 'Delhi NCR' },
  { name: 'Vasant Vihar', pincode: '110057', city: 'Delhi NCR' },
  { name: 'Vikaspuri', pincode: '110018', city: 'Delhi NCR' },
]

const HYDERABAD: LocalityOption[] = [
  { name: 'Ameerpet', pincode: '500016', city: 'Hyderabad' },
  { name: 'Banjara Hills', pincode: '500034', city: 'Hyderabad' },
  { name: 'Begumpet', pincode: '500016', city: 'Hyderabad' },
  { name: 'Chanda Nagar', pincode: '500050', city: 'Hyderabad' },
  { name: 'Compaq Circle', pincode: '500081', city: 'Hyderabad' },
  { name: 'Financial District', pincode: '500032', city: 'Hyderabad' },
  { name: 'Gachibowli', pincode: '500032', city: 'Hyderabad' },
  { name: 'Hitech City', pincode: '500081', city: 'Hyderabad' },
  { name: 'Jubilee Hills', pincode: '500033', city: 'Hyderabad' },
  { name: 'Kondapur', pincode: '500084', city: 'Hyderabad' },
  { name: 'Kukatpally', pincode: '500072', city: 'Hyderabad' },
  { name: 'LB Nagar', pincode: '500074', city: 'Hyderabad' },
  { name: 'Madhapur', pincode: '500081', city: 'Hyderabad' },
  { name: 'Manikonda', pincode: '500089', city: 'Hyderabad' },
  { name: 'Miyapur', pincode: '500049', city: 'Hyderabad' },
  { name: 'Nallagandla', pincode: '500019', city: 'Hyderabad' },
  { name: 'Narsingi', pincode: '500075', city: 'Hyderabad' },
  { name: 'Patancheruvu', pincode: '502319', city: 'Hyderabad' },
  { name: 'Puppalaguda', pincode: '500089', city: 'Hyderabad' },
  { name: 'Sainikpuri', pincode: '500094', city: 'Hyderabad' },
  { name: 'Secunderabad', pincode: '500003', city: 'Hyderabad' },
  { name: 'Serilingampally', pincode: '500019', city: 'Hyderabad' },
  { name: 'Tolichowki', pincode: '500008', city: 'Hyderabad' },
  { name: 'Uppal', pincode: '500039', city: 'Hyderabad' },
]

const CHENNAI: LocalityOption[] = [
  { name: 'Adyar', pincode: '600020', city: 'Chennai' },
  { name: 'Alwarpet', pincode: '600018', city: 'Chennai' },
  { name: 'Anna Nagar', pincode: '600040', city: 'Chennai' },
  { name: 'Besant Nagar', pincode: '600090', city: 'Chennai' },
  { name: 'Chromepet', pincode: '600044', city: 'Chennai' },
  { name: 'ECR', pincode: '600119', city: 'Chennai' },
  { name: 'Egmore', pincode: '600008', city: 'Chennai' },
  { name: 'Guindy', pincode: '600032', city: 'Chennai' },
  { name: 'Kelambakkam', pincode: '603103', city: 'Chennai' },
  { name: 'Kilpauk', pincode: '600010', city: 'Chennai' },
  { name: 'Kodambakkam', pincode: '600024', city: 'Chennai' },
  { name: 'Kolathur', pincode: '600099', city: 'Chennai' },
  { name: 'Madipakkam', pincode: '600091', city: 'Chennai' },
  { name: 'Mylapore', pincode: '600004', city: 'Chennai' },
  { name: 'Nungambakkam', pincode: '600034', city: 'Chennai' },
  { name: 'OMR', pincode: '600097', city: 'Chennai' },
  { name: 'Perambur', pincode: '600011', city: 'Chennai' },
  { name: 'Porur', pincode: '600116', city: 'Chennai' },
  { name: 'T Nagar', pincode: '600017', city: 'Chennai' },
  { name: 'Tambaram', pincode: '600045', city: 'Chennai' },
  { name: 'Thiruvanmiyur', pincode: '600041', city: 'Chennai' },
  { name: 'Velachery', pincode: '600042', city: 'Chennai' },
  { name: 'Virugambakkam', pincode: '600092', city: 'Chennai' },
]

const KOLKATA: LocalityOption[] = [
  { name: 'Alipore', pincode: '700027', city: 'Kolkata' },
  { name: 'Ballygunge', pincode: '700019', city: 'Kolkata' },
  { name: 'Behala', pincode: '700034', city: 'Kolkata' },
  { name: 'Dum Dum', pincode: '700028', city: 'Kolkata' },
  { name: 'Gariahat', pincode: '700029', city: 'Kolkata' },
  { name: 'Howrah', pincode: '711101', city: 'Kolkata' },
  { name: 'Jadavpur', pincode: '700032', city: 'Kolkata' },
  { name: 'Kankurgachi', pincode: '700054', city: 'Kolkata' },
  { name: 'Lake Town', pincode: '700089', city: 'Kolkata' },
  { name: 'New Alipore', pincode: '700053', city: 'Kolkata' },
  { name: 'New Town', pincode: '700156', city: 'Kolkata' },
  { name: 'Park Street', pincode: '700016', city: 'Kolkata' },
  { name: 'Rajarhat', pincode: '700135', city: 'Kolkata' },
  { name: 'Salt Lake', pincode: '700064', city: 'Kolkata' },
  { name: 'Shyambazar', pincode: '700004', city: 'Kolkata' },
  { name: 'Tollygunge', pincode: '700033', city: 'Kolkata' },
]

const AHMEDABAD: LocalityOption[] = [
  { name: 'Ambawadi', pincode: '380015', city: 'Ahmedabad' },
  { name: 'Bopal', pincode: '380058', city: 'Ahmedabad' },
  { name: 'CG Road', pincode: '380006', city: 'Ahmedabad' },
  { name: 'Drive In Road', pincode: '380054', city: 'Ahmedabad' },
  { name: 'Ghatlodiya', pincode: '380061', city: 'Ahmedabad' },
  { name: 'Gota', pincode: '382481', city: 'Ahmedabad' },
  { name: 'Jodhpur', pincode: '380015', city: 'Ahmedabad' },
  { name: 'Maninagar', pincode: '380008', city: 'Ahmedabad' },
  { name: 'Memnagar', pincode: '380052', city: 'Ahmedabad' },
  { name: 'Navrangpura', pincode: '380009', city: 'Ahmedabad' },
  { name: 'Prahlad Nagar', pincode: '380015', city: 'Ahmedabad' },
  { name: 'Prahladnagar Garden', pincode: '380051', city: 'Ahmedabad' },
  { name: 'Satellite', pincode: '380015', city: 'Ahmedabad' },
  { name: 'Science City Road', pincode: '380060', city: 'Ahmedabad' },
  { name: 'SG Highway', pincode: '380054', city: 'Ahmedabad' },
  { name: 'Shela', pincode: '380058', city: 'Ahmedabad' },
  { name: 'Thaltej', pincode: '380054', city: 'Ahmedabad' },
  { name: 'Vastrapur', pincode: '380015', city: 'Ahmedabad' },
  { name: 'Vejalpur', pincode: '380051', city: 'Ahmedabad' },
]

export const ALL_LOCALITIES: LocalityOption[] = [
  ...MUMBAI,
  ...PUNE,
  ...BANGALORE,
  ...DELHI_NCR,
  ...HYDERABAD,
  ...CHENNAI,
  ...KOLKATA,
  ...AHMEDABAD,
]

// Returns localities filtered to the selected city, sorted alphabetically.
export function getLocalitiesForCity(city: string): LocalityOption[] {
  // Normalise: "Bangalore" and "Bengaluru" both map to the same list
  const normalised = city.toLowerCase().replace('bengaluru', 'bangalore')
  return ALL_LOCALITIES.filter(
    (l) => l.city.toLowerCase().replace('bengaluru', 'bangalore') === normalised,
  ).sort((a, b) => a.name.localeCompare(b.name))
}

// Fuzzy filter: returns entries where the name contains the query (case-insensitive).
export function filterLocalities(localities: LocalityOption[], query: string): LocalityOption[] {
  const q = query.toLowerCase().trim()
  if (!q) return localities
  return localities.filter((l) => l.name.toLowerCase().includes(q))
}
